-- DATOS BBDD APP CONCESIONARIO -- 
	-- CREACIÓN DE TABLAS
		CREATE TABLE CONC_VEHICULOS (
			ID_VEHICULO NUMBER(9) CONSTRAINT VEH_ID_PK PRIMARY KEY,
			NUM_BASTIDOR NUMBER(20) NOT NULL,
			MARCA VARCHAR2(30) NOT NULL,
			MODELO VARCHAR2 (50) NOT NULL,
			TIPO_MOTOR VARCHAR2(30) NOT NULL,
			FECHA_FAB DATE NOT NULL,
			FECHA_MAT DATE,
			TIPO_VEH VARCHAR2 (50) NOT NULL,
			COLOR VARCHAR2 (50) NOT NULL,
			POTENCIA VARCHAR2 (6) NOT NULL
		);

		CREATE TABLE CONC_EMPLE (
			ID_EMPLE NUMBER(9) CONSTRAINT EMP_ID_PK PRIMARY KEY,
			NOMBRE VARCHAR2(30) NOT NULL,
			APELLIDOS VARCHAR2(80) NOT NULL,
			FECHA_INI DATE NOT NULL,
			FECHA_FIN DATE,
			TELEFONO VARCHAR2 (12) NOT NULL,
			DIRECCION VARCHAR2 (70) NOT NULL,
			NUM_VENTAS NUMBER (3) NOT NULL,
			CARGO VARCHAR2(50) NOT NULL
		);

		CREATE TABLE CONC_CLIENTES (
			ID_CLI NUMBER(9) CONSTRAINT CLI_ID_PK PRIMARY KEY,
			NOMBRE VARCHAR2(30) NOT NULL,
			APELLIDOS VARCHAR2(80) NOT NULL,
			FECHA_ALTA DATE NOT NULL,
			TELEFONO VARCHAR2 (12) NOT NULL,
			NUM_COMPRAS NUMBER (4)
		);

		CREATE TABLE CONC_PRESUPUESTOS (
			ID_VEHICULO NUMBER(9),
			ID_CLIENTE NUMBER(9),
			NUM_PPTO VARCHAR2(10),
			CONSTRAINT VEH_ID_VEH_ID_CLI_PK PRIMARY KEY (ID_VEHICULO, ID_CLI),
			CONSTRAINT VEH_ID_VEH_FK REFERENCES CONC_VEHICULOS (ID_VEHICULO),
			CONSTRAINT CLI_ID_CLI_FK REFERENCES CONC_CLIENTES (ID_CLI),
		);

		-- SECUENCIAS 
			CREATE SEQUENCE CON_VEH_ID_CLI_SEQ
			START WITH 1
				INCREMENT BY 1
				MAXVALUE 99999
				MINVALUE 1
				CACHE 4
				ORDER;

			CREATE SEQUENCE CON_EMPLE_ID_EMPLE_SEQ
			START WITH 1
				INCREMENT BY 1
				MAXVALUE 99999
				MINVALUE 1
				CACHE 4
				ORDER;

			-- ¿ORDENAR COD_CLIENTE? 
			CREATE SEQUENCE CON_CLIENTES_ID_CLI_SEQ
			START WITH 1
				INCREMENT BY 1
				MAXVALUE 99999
				MINVALUE 1
				CACHE 4
				ORDER;
				
			-- ¿ORDENAR PRESUPUESTOS POR NÚMERO?
			CREATE SEQUENCE CON_PPTO_NUM_PPTO_SEQ
			START WITH 1
				INCREMENT BY 1
				MAXVALUE 99999
				MINVALUE 1
				CACHE 4
				ORDER;


		-- INSERTS
			
			BEGIN
				INSERT INTO CONC_EMPLE
				VALUES (CON_EMPLE_ID_EMPLE_SEQ.NEXTVAL, 'MARCO', 'MARTINEZ COLLADO', '20/02/2019', '', '+34 569874125', 'C/ OLMO, 12', 231, 'COMERCIAL');
				INSERT INTO CONC_EMPLE
				VALUES (CON_EMPLE_ID_EMPLE_SEQ.NEXTVAL, 'LUIS', 'GÓMEZ DÍAZ', '10/11/2018', '', '+34 569874521', 'C/ MAYOR, 2', '', 'DIRECTOR');
				INSERT INTO CONC_EMPLE
				VALUES (CON_EMPLE_ID_EMPLE_SEQ.NEXTVAL, 'MARÍA', 'MOLLA LÓPEZ', '20/02/2019', '', '+34 599874125', 'C/ HUERTAS, 1', '' , 'ADMINISTRATIVO');
				INSERT INTO CONC_EMPLE
				VALUES (CON_EMPLE_ID_EMPLE_SEQ.NEXTVAL, 'MARTA', 'SORIA MARAÑÓN', '20/02/2019', '', '+34 569478125', 'C/ GRAN VÍA, 21', '', 'CONTABLE');
			END;